<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="ROBOTS" content="ALL" />
    <meta http-equiv="imagetoolbar" content="no" />
    <meta name="MSSmartTagsPreventParsing" content="true" />
    <meta name="Copyright" content="Django Software Foundation" />
    <meta name="keywords" content="Python, Django, framework, open-source" />
    <meta name="description" content="" />

    <!-- Favicons -->
    <link rel="apple-touch-icon" href="/s/img/icon-touch.e4872c4da341.png">
    <link rel="icon" sizes="192x192" href="/s/img/icon-touch.e4872c4da341.png">
    <link rel="shortcut icon" href="/s/img/favicon.6dbf28c0650e.ico">
    <meta name="msapplication-TileColor" content="#113228">
    <meta name="msapplication-TileImage" content="/s/img/icon-tile.b01ac0ef9f67.png">

    <title>Django Exceptions | Django documentation | Django</title>

    <link rel="stylesheet" href="/s/css/output.336367358ac1.css" >
    <script src="/s/js/lib/webfontloader/webfontloader.e75218f5f090.js"></script>
    <script>
    WebFont.load({
      custom: {
        families: ['FontAwesome', 'Fira+Mono'],
      },
      google: {
        families: ['Roboto:400italic,700italic,300,700,400:latin'
        ]
      },
      classes: false,
      events: false,
      timeout: 1000
    });
    </script>
    <script src="/s/js/lib/modernizr.3b36762e418a.js"></script>
    
  
    
      
    
  
  <link rel="canonical" href="https://docs.djangoproject.com/en/1.10/ref/exceptions/">
  
    
        
          
        
        
        <link rel="alternate"
           hreflang="el"
           href="https://docs.djangoproject.com/el/1.10/ref/exceptions/">
    
        
          
        
        
        <link rel="alternate"
           hreflang="x-default"
           href="https://docs.djangoproject.com/en/1.10/ref/exceptions/">
        
        <link rel="alternate"
           hreflang="en"
           href="https://docs.djangoproject.com/en/1.10/ref/exceptions/">
    
        
          
        
        
        <link rel="alternate"
           hreflang="es"
           href="https://docs.djangoproject.com/es/1.10/ref/exceptions/">
    
        
          
        
        
        <link rel="alternate"
           hreflang="fr"
           href="https://docs.djangoproject.com/fr/1.10/ref/exceptions/">
    
        
          
        
        
        <link rel="alternate"
           hreflang="id"
           href="https://docs.djangoproject.com/id/1.10/ref/exceptions/">
    
        
          
        
        
        <link rel="alternate"
           hreflang="ja"
           href="https://docs.djangoproject.com/ja/1.10/ref/exceptions/">
    
        
          
        
        
        <link rel="alternate"
           hreflang="pl"
           href="https://docs.djangoproject.com/pl/1.10/ref/exceptions/">
    
        
          
        
        
        <link rel="alternate"
           hreflang="pt-br"
           href="https://docs.djangoproject.com/pt-br/1.10/ref/exceptions/">
    
  

  <link rel="search"
        type="application/opensearchdescription+xml"
        href="https://docs.djangoproject.com/en/1.10/search/description/"
        title="Django documentation">

  </head>

  <body id="generic" class="">

    <div role="banner" id="top">
  <div class="container">
    <a class="logo" href="https://www.djangoproject.com/">Django</a>
    <p class="meta">The web framework for perfectionists with deadlines.</p>
    <div role="navigation">
      <ul>
        <li>
          <a href="https://www.djangoproject.com/start/overview/">Overview</a>
        </li>
        <li>
          <a href="https://www.djangoproject.com/download/">Download</a>
        </li>
        <li class="active">
          <a href="https://docs.djangoproject.com/">Documentation</a>
        </li>
        <li>
          <a href="https://www.djangoproject.com/weblog/">News</a>
        </li>
        <li>
          <a href="https://www.djangoproject.com/community/">Community</a>
        </li>
        <li>
          <a href="https://code.djangoproject.com/">Code</a>
        </li>
        <li>
          <a href="https://www.djangoproject.com/foundation/">About</a>
        </li>
        <li>
          <a href="https://www.djangoproject.com/fundraising/">&#9829; Donate</a>
        </li>
      </ul>
    </div>
  </div>
</div>


    <div class="copy-banner">
      <div class="container">
        
  <h1><a href="https://docs.djangoproject.com/en/1.10/">Documentation</a></h1>

      </div>
    </div>
    <div id="billboard"></div>

    <div class="container sidebar-right">
      <div role="main">

        
          
        

        
<div id="version-switcher">
  <ul id="doc-languages" class="language-switcher">
  
  
  <li class="other">
    
      
    
    <a href="https://docs.djangoproject.com/el/1.10/ref/exceptions/">el</a>
  </li>
  
  
  
  
  
  <li class="other">
    
      
    
    <a href="https://docs.djangoproject.com/es/1.10/ref/exceptions/">es</a>
  </li>
  
  
  
  <li class="other">
    
      
    
    <a href="https://docs.djangoproject.com/fr/1.10/ref/exceptions/">fr</a>
  </li>
  
  
  
  <li class="other">
    
      
    
    <a href="https://docs.djangoproject.com/id/1.10/ref/exceptions/">id</a>
  </li>
  
  
  
  <li class="other">
    
      
    
    <a href="https://docs.djangoproject.com/ja/1.10/ref/exceptions/">ja</a>
  </li>
  
  
  
  <li class="other">
    
      
    
    <a href="https://docs.djangoproject.com/pl/1.10/ref/exceptions/">pl</a>
  </li>
  
  
  
  <li class="other">
    
      
    
    <a href="https://docs.djangoproject.com/pt-br/1.10/ref/exceptions/">pt-br</a>
  </li>
  
  
    <li class="current"
        title="Click on the links on the left to switch to another language.">
      <span>Language: <strong>en</strong></span>
    </li>
  </ul>

  
  <ul id="doc-versions" class="version-switcher">
    
    
    <li class="other">
      
        
      
      <a href="https://docs.djangoproject.com/en/1.7/ref/exceptions/">1.7</a>
    </li>
    
    
    
    <li class="other">
      
        
      
      <a href="https://docs.djangoproject.com/en/1.8/ref/exceptions/">1.8</a>
    </li>
    
    
    
    <li class="other">
      
        
      
      <a href="https://docs.djangoproject.com/en/1.9/ref/exceptions/">1.9</a>
    </li>
    
    
    
    
    
    <li class="other">
      
        
      
      <a href="https://docs.djangoproject.com/en/dev/ref/exceptions/">dev</a>
    </li>
    
    
    <li class="current"
        title="This document describes Django 1.10. Click on the links on the left to see other versions.">
       <span>Documentation version:
         <strong>1.10</strong>
       </span>
    </li>
  </ul>
</div>


<div id="docs-content">
<div class="section" id="s-django-exceptions">
<span id="django-exceptions"></span><h1>Django Exceptions<a class="headerlink" href="#django-exceptions" title="Permalink to this headline">¶</a></h1>
<p>Django raises some of its own exceptions as well as standard Python exceptions.</p>
<div class="section" id="s-module-django.core.exceptions">
<span id="s-django-core-exceptions"></span><span id="module-django.core.exceptions"></span><span id="django-core-exceptions"></span><h2>Django Core Exceptions<a class="headerlink" href="#module-django.core.exceptions" title="Permalink to this headline">¶</a></h2>
<p>Django core exception classes are defined in <code class="docutils literal"><span class="pre">django.core.exceptions</span></code>.</p>
<div class="section" id="s-appregistrynotready">
<span id="appregistrynotready"></span><h3><code class="docutils literal"><span class="pre">AppRegistryNotReady</span></code><a class="headerlink" href="#appregistrynotready" title="Permalink to this headline">¶</a></h3>
<dl class="exception">
<dt id="django.core.exceptions.AppRegistryNotReady">
<em class="property">exception </em><code class="descname">AppRegistryNotReady</code><a class="reference internal" href="../../_modules/django/core/exceptions/#AppRegistryNotReady"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#django.core.exceptions.AppRegistryNotReady" title="Permalink to this definition">¶</a></dt>
<dd><p>This exception is raised when attempting to use models before the <a class="reference internal" href="../applications/#app-loading-process"><span class="std std-ref">app
loading process</span></a>, which initializes the ORM, is
complete.</p>
</dd></dl>

</div>
<div class="section" id="s-objectdoesnotexist">
<span id="objectdoesnotexist"></span><h3><code class="docutils literal"><span class="pre">ObjectDoesNotExist</span></code><a class="headerlink" href="#objectdoesnotexist" title="Permalink to this headline">¶</a></h3>
<dl class="exception">
<dt id="django.core.exceptions.ObjectDoesNotExist">
<em class="property">exception </em><code class="descname">ObjectDoesNotExist</code><a class="reference internal" href="../../_modules/django/core/exceptions/#ObjectDoesNotExist"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#django.core.exceptions.ObjectDoesNotExist" title="Permalink to this definition">¶</a></dt>
<dd><p>The base class for <a class="reference internal" href="../models/instances/#django.db.models.Model.DoesNotExist" title="django.db.models.Model.DoesNotExist"><code class="xref py py-exc docutils literal"><span class="pre">DoesNotExist</span></code></a> exceptions;
a <code class="docutils literal"><span class="pre">try/except</span></code> for <code class="docutils literal"><span class="pre">ObjectDoesNotExist</span></code> will catch
<a class="reference internal" href="../models/instances/#django.db.models.Model.DoesNotExist" title="django.db.models.Model.DoesNotExist"><code class="xref py py-exc docutils literal"><span class="pre">DoesNotExist</span></code></a> exceptions for all models.</p>
<p>See <a class="reference internal" href="../models/querysets/#django.db.models.query.QuerySet.get" title="django.db.models.query.QuerySet.get"><code class="xref py py-meth docutils literal"><span class="pre">get()</span></code></a> for further information
on <a class="reference internal" href="#django.core.exceptions.ObjectDoesNotExist" title="django.core.exceptions.ObjectDoesNotExist"><code class="xref py py-exc docutils literal"><span class="pre">ObjectDoesNotExist</span></code></a> and <a class="reference internal" href="../models/instances/#django.db.models.Model.DoesNotExist" title="django.db.models.Model.DoesNotExist"><code class="xref py py-exc docutils literal"><span class="pre">DoesNotExist</span></code></a>.</p>
</dd></dl>

</div>
<div class="section" id="s-fielddoesnotexist">
<span id="fielddoesnotexist"></span><h3><code class="docutils literal"><span class="pre">FieldDoesNotExist</span></code><a class="headerlink" href="#fielddoesnotexist" title="Permalink to this headline">¶</a></h3>
<dl class="exception">
<dt id="django.core.exceptions.FieldDoesNotExist">
<em class="property">exception </em><code class="descname">FieldDoesNotExist</code><a class="reference internal" href="../../_modules/django/core/exceptions/#FieldDoesNotExist"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#django.core.exceptions.FieldDoesNotExist" title="Permalink to this definition">¶</a></dt>
<dd><p>The <code class="docutils literal"><span class="pre">FieldDoesNotExist</span></code> exception is raised by a model&#8217;s
<code class="docutils literal"><span class="pre">_meta.get_field()</span></code> method when the requested field does not exist on the
model or on the model&#8217;s parents.</p>
</dd></dl>

</div>
<div class="section" id="s-multipleobjectsreturned">
<span id="multipleobjectsreturned"></span><h3><code class="docutils literal"><span class="pre">MultipleObjectsReturned</span></code><a class="headerlink" href="#multipleobjectsreturned" title="Permalink to this headline">¶</a></h3>
<dl class="exception">
<dt id="django.core.exceptions.MultipleObjectsReturned">
<em class="property">exception </em><code class="descname">MultipleObjectsReturned</code><a class="reference internal" href="../../_modules/django/core/exceptions/#MultipleObjectsReturned"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#django.core.exceptions.MultipleObjectsReturned" title="Permalink to this definition">¶</a></dt>
<dd><p>The <a class="reference internal" href="#django.core.exceptions.MultipleObjectsReturned" title="django.core.exceptions.MultipleObjectsReturned"><code class="xref py py-exc docutils literal"><span class="pre">MultipleObjectsReturned</span></code></a> exception is raised by a query if only
one object is expected, but multiple objects are returned. A base version
of this exception is provided in <a class="reference internal" href="#module-django.core.exceptions" title="django.core.exceptions: Django core exceptions"><code class="xref py py-mod docutils literal"><span class="pre">django.core.exceptions</span></code></a>; each model
class contains a subclassed version that can be used to identify the
specific object type that has returned multiple objects.</p>
<p>See <a class="reference internal" href="../models/querysets/#django.db.models.query.QuerySet.get" title="django.db.models.query.QuerySet.get"><code class="xref py py-meth docutils literal"><span class="pre">get()</span></code></a> for further information.</p>
</dd></dl>

</div>
<div class="section" id="s-suspiciousoperation">
<span id="suspiciousoperation"></span><h3><code class="docutils literal"><span class="pre">SuspiciousOperation</span></code><a class="headerlink" href="#suspiciousoperation" title="Permalink to this headline">¶</a></h3>
<dl class="exception">
<dt id="django.core.exceptions.SuspiciousOperation">
<em class="property">exception </em><code class="descname">SuspiciousOperation</code><a class="reference internal" href="../../_modules/django/core/exceptions/#SuspiciousOperation"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#django.core.exceptions.SuspiciousOperation" title="Permalink to this definition">¶</a></dt>
<dd><p>The <a class="reference internal" href="#django.core.exceptions.SuspiciousOperation" title="django.core.exceptions.SuspiciousOperation"><code class="xref py py-exc docutils literal"><span class="pre">SuspiciousOperation</span></code></a> exception is raised when a user has
performed an operation that should be considered suspicious from a security
perspective, such as tampering with a session cookie. Subclasses of
<code class="docutils literal"><span class="pre">SuspiciousOperation</span></code> include:</p>
<ul class="simple">
<li><code class="docutils literal"><span class="pre">DisallowedHost</span></code></li>
<li><code class="docutils literal"><span class="pre">DisallowedModelAdminLookup</span></code></li>
<li><code class="docutils literal"><span class="pre">DisallowedModelAdminToField</span></code></li>
<li><code class="docutils literal"><span class="pre">DisallowedRedirect</span></code></li>
<li><code class="docutils literal"><span class="pre">InvalidSessionKey</span></code></li>
<li><code class="docutils literal"><span class="pre">RequestDataTooBig</span></code></li>
<li><code class="docutils literal"><span class="pre">SuspiciousFileOperation</span></code></li>
<li><code class="docutils literal"><span class="pre">SuspiciousMultipartForm</span></code></li>
<li><code class="docutils literal"><span class="pre">SuspiciousSession</span></code></li>
<li><code class="docutils literal"><span class="pre">TooManyFieldsSent</span></code></li>
</ul>
<p>If a <code class="docutils literal"><span class="pre">SuspiciousOperation</span></code> exception reaches the WSGI handler level it is
logged at the <code class="docutils literal"><span class="pre">Error</span></code> level and results in
a <a class="reference internal" href="../request-response/#django.http.HttpResponseBadRequest" title="django.http.HttpResponseBadRequest"><code class="xref py py-class docutils literal"><span class="pre">HttpResponseBadRequest</span></code></a>. See the <a class="reference internal" href="../../topics/logging/"><span class="doc">logging
documentation</span></a> for more information.</p>
</dd></dl>

</div>
<div class="section" id="s-permissiondenied">
<span id="permissiondenied"></span><h3><code class="docutils literal"><span class="pre">PermissionDenied</span></code><a class="headerlink" href="#permissiondenied" title="Permalink to this headline">¶</a></h3>
<dl class="exception">
<dt id="django.core.exceptions.PermissionDenied">
<em class="property">exception </em><code class="descname">PermissionDenied</code><a class="reference internal" href="../../_modules/django/core/exceptions/#PermissionDenied"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#django.core.exceptions.PermissionDenied" title="Permalink to this definition">¶</a></dt>
<dd><p>The <a class="reference internal" href="#django.core.exceptions.PermissionDenied" title="django.core.exceptions.PermissionDenied"><code class="xref py py-exc docutils literal"><span class="pre">PermissionDenied</span></code></a> exception is raised when a user does not have
permission to perform the action requested.</p>
</dd></dl>

</div>
<div class="section" id="s-viewdoesnotexist">
<span id="viewdoesnotexist"></span><h3><code class="docutils literal"><span class="pre">ViewDoesNotExist</span></code><a class="headerlink" href="#viewdoesnotexist" title="Permalink to this headline">¶</a></h3>
<dl class="exception">
<dt id="django.core.exceptions.ViewDoesNotExist">
<em class="property">exception </em><code class="descname">ViewDoesNotExist</code><a class="reference internal" href="../../_modules/django/core/exceptions/#ViewDoesNotExist"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#django.core.exceptions.ViewDoesNotExist" title="Permalink to this definition">¶</a></dt>
<dd><p>The <a class="reference internal" href="#django.core.exceptions.ViewDoesNotExist" title="django.core.exceptions.ViewDoesNotExist"><code class="xref py py-exc docutils literal"><span class="pre">ViewDoesNotExist</span></code></a> exception is raised by
<a class="reference internal" href="../urlresolvers/#module-django.urls" title="django.urls"><code class="xref py py-mod docutils literal"><span class="pre">django.urls</span></code></a> when a requested view does not exist.</p>
</dd></dl>

</div>
<div class="section" id="s-middlewarenotused">
<span id="middlewarenotused"></span><h3><code class="docutils literal"><span class="pre">MiddlewareNotUsed</span></code><a class="headerlink" href="#middlewarenotused" title="Permalink to this headline">¶</a></h3>
<dl class="exception">
<dt id="django.core.exceptions.MiddlewareNotUsed">
<em class="property">exception </em><code class="descname">MiddlewareNotUsed</code><a class="reference internal" href="../../_modules/django/core/exceptions/#MiddlewareNotUsed"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#django.core.exceptions.MiddlewareNotUsed" title="Permalink to this definition">¶</a></dt>
<dd><p>The <a class="reference internal" href="#django.core.exceptions.MiddlewareNotUsed" title="django.core.exceptions.MiddlewareNotUsed"><code class="xref py py-exc docutils literal"><span class="pre">MiddlewareNotUsed</span></code></a> exception is raised when a middleware is not
used in the server configuration.</p>
</dd></dl>

</div>
<div class="section" id="s-improperlyconfigured">
<span id="improperlyconfigured"></span><h3><code class="docutils literal"><span class="pre">ImproperlyConfigured</span></code><a class="headerlink" href="#improperlyconfigured" title="Permalink to this headline">¶</a></h3>
<dl class="exception">
<dt id="django.core.exceptions.ImproperlyConfigured">
<em class="property">exception </em><code class="descname">ImproperlyConfigured</code><a class="reference internal" href="../../_modules/django/core/exceptions/#ImproperlyConfigured"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#django.core.exceptions.ImproperlyConfigured" title="Permalink to this definition">¶</a></dt>
<dd><p>The <a class="reference internal" href="#django.core.exceptions.ImproperlyConfigured" title="django.core.exceptions.ImproperlyConfigured"><code class="xref py py-exc docutils literal"><span class="pre">ImproperlyConfigured</span></code></a> exception is raised when Django is
somehow improperly configured &#8211; for example, if a value in <code class="docutils literal"><span class="pre">settings.py</span></code>
is incorrect or unparseable.</p>
</dd></dl>

</div>
<div class="section" id="s-fielderror">
<span id="fielderror"></span><h3><code class="docutils literal"><span class="pre">FieldError</span></code><a class="headerlink" href="#fielderror" title="Permalink to this headline">¶</a></h3>
<dl class="exception">
<dt id="django.core.exceptions.FieldError">
<em class="property">exception </em><code class="descname">FieldError</code><a class="reference internal" href="../../_modules/django/core/exceptions/#FieldError"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#django.core.exceptions.FieldError" title="Permalink to this definition">¶</a></dt>
<dd><p>The <a class="reference internal" href="#django.core.exceptions.FieldError" title="django.core.exceptions.FieldError"><code class="xref py py-exc docutils literal"><span class="pre">FieldError</span></code></a> exception is raised when there is a problem with a
model field. This can happen for several reasons:</p>
<ul class="simple">
<li>A field in a model clashes with a field of the same name from an
abstract base class</li>
<li>An infinite loop is caused by ordering</li>
<li>A keyword cannot be parsed from the filter parameters</li>
<li>A field cannot be determined from a keyword in the query
parameters</li>
<li>A join is not permitted on the specified field</li>
<li>A field name is invalid</li>
<li>A query contains invalid order_by arguments</li>
</ul>
</dd></dl>

</div>
<div class="section" id="s-validationerror">
<span id="validationerror"></span><h3><code class="docutils literal"><span class="pre">ValidationError</span></code><a class="headerlink" href="#validationerror" title="Permalink to this headline">¶</a></h3>
<dl class="exception">
<dt id="django.core.exceptions.ValidationError">
<em class="property">exception </em><code class="descname">ValidationError</code><a class="reference internal" href="../../_modules/django/core/exceptions/#ValidationError"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#django.core.exceptions.ValidationError" title="Permalink to this definition">¶</a></dt>
<dd><p>The <a class="reference internal" href="#django.core.exceptions.ValidationError" title="django.core.exceptions.ValidationError"><code class="xref py py-exc docutils literal"><span class="pre">ValidationError</span></code></a> exception is raised when data fails form or
model field validation. For more information about validation, see
<a class="reference internal" href="../forms/validation/"><span class="doc">Form and Field Validation</span></a>,
<a class="reference internal" href="../models/instances/#validating-objects"><span class="std std-ref">Model Field Validation</span></a> and the
<a class="reference internal" href="../validators/"><span class="doc">Validator Reference</span></a>.</p>
</dd></dl>

<div class="section" id="s-non-field-errors">
<span id="non-field-errors"></span><h4><code class="docutils literal"><span class="pre">NON_FIELD_ERRORS</span></code><a class="headerlink" href="#non-field-errors" title="Permalink to this headline">¶</a></h4>
<dl class="data">
<dt id="django.core.exceptions.NON_FIELD_ERRORS">
<code class="descname">NON_FIELD_ERRORS</code><a class="headerlink" href="#django.core.exceptions.NON_FIELD_ERRORS" title="Permalink to this definition">¶</a></dt>
<dd></dd></dl>

<p><code class="docutils literal"><span class="pre">ValidationError</span></code>s that don&#8217;t belong to a particular field in a form
or model are classified as <code class="docutils literal"><span class="pre">NON_FIELD_ERRORS</span></code>. This constant is used
as a key in dictionaries that otherwise map fields to their respective
list of errors.</p>
</div>
</div>
</div>
<div class="section" id="s-url-resolver-exceptions">
<span id="url-resolver-exceptions"></span><h2>URL Resolver exceptions<a class="headerlink" href="#url-resolver-exceptions" title="Permalink to this headline">¶</a></h2>
<p>URL Resolver exceptions are defined in <code class="docutils literal"><span class="pre">django.urls</span></code>.</p>
<div class="deprecated">
<p><span class="versionmodified">Deprecated since version 1.10: </span>In older versions, these exceptions are located in
<code class="docutils literal"><span class="pre">django.core.urlresolvers</span></code>. Importing from the old location will continue
to work until Django 2.0.</p>
</div>
<div class="section" id="s-resolver404">
<span id="resolver404"></span><h3><code class="docutils literal"><span class="pre">Resolver404</span></code><a class="headerlink" href="#resolver404" title="Permalink to this headline">¶</a></h3>
<dl class="exception">
<dt id="django.urls.Resolver404">
<em class="property">exception </em><code class="descname">Resolver404</code><a class="reference internal" href="../../_modules/django/urls/exceptions/#Resolver404"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#django.urls.Resolver404" title="Permalink to this definition">¶</a></dt>
<dd><p>The <a class="reference internal" href="#django.urls.Resolver404" title="django.urls.Resolver404"><code class="xref py py-exc docutils literal"><span class="pre">Resolver404</span></code></a> exception is raised by
<a class="reference internal" href="../urlresolvers/#django.urls.resolve" title="django.urls.resolve"><code class="xref py py-func docutils literal"><span class="pre">resolve()</span></code></a> if the path passed to <code class="docutils literal"><span class="pre">resolve()</span></code> doesn&#8217;t
map to a view. It&#8217;s a subclass of <a class="reference internal" href="../../topics/http/views/#django.http.Http404" title="django.http.Http404"><code class="xref py py-class docutils literal"><span class="pre">django.http.Http404</span></code></a>.</p>
</dd></dl>

</div>
<div class="section" id="s-noreversematch">
<span id="noreversematch"></span><h3><code class="docutils literal"><span class="pre">NoReverseMatch</span></code><a class="headerlink" href="#noreversematch" title="Permalink to this headline">¶</a></h3>
<dl class="exception">
<dt id="django.urls.NoReverseMatch">
<em class="property">exception </em><code class="descname">NoReverseMatch</code><a class="reference internal" href="../../_modules/django/urls/exceptions/#NoReverseMatch"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#django.urls.NoReverseMatch" title="Permalink to this definition">¶</a></dt>
<dd><p>The <a class="reference internal" href="#django.urls.NoReverseMatch" title="django.urls.NoReverseMatch"><code class="xref py py-exc docutils literal"><span class="pre">NoReverseMatch</span></code></a> exception is raised by <a class="reference internal" href="../urlresolvers/#module-django.urls" title="django.urls"><code class="xref py py-mod docutils literal"><span class="pre">django.urls</span></code></a> when a
matching URL in your URLconf cannot be identified based on the parameters
supplied.</p>
</dd></dl>

</div>
</div>
<div class="section" id="s-database-exceptions">
<span id="database-exceptions"></span><h2>Database Exceptions<a class="headerlink" href="#database-exceptions" title="Permalink to this headline">¶</a></h2>
<p>Database exceptions may be imported from <code class="docutils literal"><span class="pre">django.db</span></code>.</p>
<p>Django wraps the standard database exceptions so that your Django code has a
guaranteed common implementation of these classes.</p>
<dl class="exception">
<dt id="django.db.Error">
<em class="property">exception </em><code class="descname">Error</code><a class="reference internal" href="../../_modules/django/db/utils/#Error"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#django.db.Error" title="Permalink to this definition">¶</a></dt>
<dd></dd></dl>

<dl class="exception">
<dt id="django.db.InterfaceError">
<em class="property">exception </em><code class="descname">InterfaceError</code><a class="reference internal" href="../../_modules/django/db/utils/#InterfaceError"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#django.db.InterfaceError" title="Permalink to this definition">¶</a></dt>
<dd></dd></dl>

<dl class="exception">
<dt id="django.db.DatabaseError">
<em class="property">exception </em><code class="descname">DatabaseError</code><a class="reference internal" href="../../_modules/django/db/utils/#DatabaseError"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#django.db.DatabaseError" title="Permalink to this definition">¶</a></dt>
<dd></dd></dl>

<dl class="exception">
<dt id="django.db.DataError">
<em class="property">exception </em><code class="descname">DataError</code><a class="reference internal" href="../../_modules/django/db/utils/#DataError"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#django.db.DataError" title="Permalink to this definition">¶</a></dt>
<dd></dd></dl>

<dl class="exception">
<dt id="django.db.OperationalError">
<em class="property">exception </em><code class="descname">OperationalError</code><a class="reference internal" href="../../_modules/django/db/utils/#OperationalError"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#django.db.OperationalError" title="Permalink to this definition">¶</a></dt>
<dd></dd></dl>

<dl class="exception">
<dt id="django.db.IntegrityError">
<em class="property">exception </em><code class="descname">IntegrityError</code><a class="reference internal" href="../../_modules/django/db/utils/#IntegrityError"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#django.db.IntegrityError" title="Permalink to this definition">¶</a></dt>
<dd></dd></dl>

<dl class="exception">
<dt id="django.db.InternalError">
<em class="property">exception </em><code class="descname">InternalError</code><a class="reference internal" href="../../_modules/django/db/utils/#InternalError"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#django.db.InternalError" title="Permalink to this definition">¶</a></dt>
<dd></dd></dl>

<dl class="exception">
<dt id="django.db.ProgrammingError">
<em class="property">exception </em><code class="descname">ProgrammingError</code><a class="reference internal" href="../../_modules/django/db/utils/#ProgrammingError"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#django.db.ProgrammingError" title="Permalink to this definition">¶</a></dt>
<dd></dd></dl>

<dl class="exception">
<dt id="django.db.NotSupportedError">
<em class="property">exception </em><code class="descname">NotSupportedError</code><a class="reference internal" href="../../_modules/django/db/utils/#NotSupportedError"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#django.db.NotSupportedError" title="Permalink to this definition">¶</a></dt>
<dd></dd></dl>

<p>The Django wrappers for database exceptions behave exactly the same as
the underlying database exceptions. See <span class="target" id="index-0"></span><a class="pep reference external" href="https://www.python.org/dev/peps/pep-0249"><strong>PEP 249</strong></a>, the Python Database API
Specification v2.0, for further information.</p>
<p>As per <span class="target" id="index-1"></span><a class="pep reference external" href="https://www.python.org/dev/peps/pep-3134"><strong>PEP 3134</strong></a>, a <code class="docutils literal"><span class="pre">__cause__</span></code> attribute is set with the original
(underlying) database exception, allowing access to any additional
information provided. (Note that this attribute is available under
both Python 2 and Python 3, although <span class="target" id="index-2"></span><a class="pep reference external" href="https://www.python.org/dev/peps/pep-3134"><strong>PEP 3134</strong></a> normally only applies
to Python 3. To avoid unexpected differences with Python 3, Django will also
ensure that the exception made available via <code class="docutils literal"><span class="pre">__cause__</span></code> has a usable
<code class="docutils literal"><span class="pre">__traceback__</span></code> attribute.)</p>
<div class="versionchanged">
<span class="title">Changed in Django 1.10:</span> <p>The <code class="docutils literal"><span class="pre">__traceback__</span></code> attribute described above was added.</p>
</div>
<dl class="exception">
<dt id="django.db.models.ProtectedError">
<em class="property">exception </em><code class="descclassname">models.</code><code class="descname">ProtectedError</code><a class="headerlink" href="#django.db.models.ProtectedError" title="Permalink to this definition">¶</a></dt>
<dd></dd></dl>

<p>Raised to prevent deletion of referenced objects when using
<a class="reference internal" href="../models/fields/#django.db.models.PROTECT" title="django.db.models.PROTECT"><code class="xref py py-attr docutils literal"><span class="pre">django.db.models.PROTECT</span></code></a>. <a class="reference internal" href="#django.db.models.ProtectedError" title="django.db.models.ProtectedError"><code class="xref py py-exc docutils literal"><span class="pre">models.ProtectedError</span></code></a> is a subclass
of <a class="reference internal" href="#django.db.IntegrityError" title="django.db.IntegrityError"><code class="xref py py-exc docutils literal"><span class="pre">IntegrityError</span></code></a>.</p>
</div>
<div class="section" id="s-http-exceptions">
<span id="http-exceptions"></span><h2>Http Exceptions<a class="headerlink" href="#http-exceptions" title="Permalink to this headline">¶</a></h2>
<p>Http exceptions may be imported from <code class="docutils literal"><span class="pre">django.http</span></code>.</p>
<div class="section" id="s-unreadableposterror">
<span id="unreadableposterror"></span><h3><code class="docutils literal"><span class="pre">UnreadablePostError</span></code><a class="headerlink" href="#unreadableposterror" title="Permalink to this headline">¶</a></h3>
<dl class="exception">
<dt id="django.http.UnreadablePostError">
<em class="property">exception </em><code class="descname">UnreadablePostError</code><a class="reference internal" href="../../_modules/django/http/request/#UnreadablePostError"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#django.http.UnreadablePostError" title="Permalink to this definition">¶</a></dt>
<dd><p><a class="reference internal" href="#django.http.UnreadablePostError" title="django.http.UnreadablePostError"><code class="xref py py-exc docutils literal"><span class="pre">UnreadablePostError</span></code></a> is raised when a user cancels an upload.</p>
</dd></dl>

</div>
</div>
<div class="section" id="s-transaction-exceptions">
<span id="transaction-exceptions"></span><h2>Transaction Exceptions<a class="headerlink" href="#transaction-exceptions" title="Permalink to this headline">¶</a></h2>
<p>Transaction exceptions are defined in <code class="docutils literal"><span class="pre">django.db.transaction</span></code>.</p>
<div class="section" id="s-transactionmanagementerror">
<span id="transactionmanagementerror"></span><h3><code class="docutils literal"><span class="pre">TransactionManagementError</span></code><a class="headerlink" href="#transactionmanagementerror" title="Permalink to this headline">¶</a></h3>
<dl class="exception">
<dt id="django.db.transaction.TransactionManagementError">
<em class="property">exception </em><code class="descname">TransactionManagementError</code><a class="reference internal" href="../../_modules/django/db/transaction/#TransactionManagementError"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#django.db.transaction.TransactionManagementError" title="Permalink to this definition">¶</a></dt>
<dd><p><a class="reference internal" href="#django.db.transaction.TransactionManagementError" title="django.db.transaction.TransactionManagementError"><code class="xref py py-exc docutils literal"><span class="pre">TransactionManagementError</span></code></a> is raised for any and all problems
related to database transactions.</p>
</dd></dl>

</div>
</div>
<div class="section" id="s-testing-framework-exceptions">
<span id="testing-framework-exceptions"></span><h2>Testing Framework Exceptions<a class="headerlink" href="#testing-framework-exceptions" title="Permalink to this headline">¶</a></h2>
<p>Exceptions provided by the <code class="docutils literal"><span class="pre">django.test</span></code> package.</p>
<div class="section" id="s-redirectcycleerror">
<span id="redirectcycleerror"></span><h3><code class="docutils literal"><span class="pre">RedirectCycleError</span></code><a class="headerlink" href="#redirectcycleerror" title="Permalink to this headline">¶</a></h3>
<dl class="exception">
<dt id="django.test.client.RedirectCycleError">
<em class="property">exception </em><code class="descclassname">client.</code><code class="descname">RedirectCycleError</code><a class="headerlink" href="#django.test.client.RedirectCycleError" title="Permalink to this definition">¶</a></dt>
<dd><p><a class="reference internal" href="#django.test.client.RedirectCycleError" title="django.test.client.RedirectCycleError"><code class="xref py py-exc docutils literal"><span class="pre">RedirectCycleError</span></code></a> is raised when the test client detects a
loop or an overly long chain of redirects.</p>
</dd></dl>

</div>
</div>
<div class="section" id="s-python-exceptions">
<span id="python-exceptions"></span><h2>Python Exceptions<a class="headerlink" href="#python-exceptions" title="Permalink to this headline">¶</a></h2>
<p>Django raises built-in Python exceptions when appropriate as well. See the
Python documentation for further information on the <a class="reference external" href="https://docs.python.org/3/library/exceptions.html#bltin-exceptions" title="(in Python v3.6)"><span>Built-in Exceptions</span></a>.</p>
</div>
</div>

</div>



<div class="browse-horizontal">
  
  <div class="left"><a href="../django-admin/"><i class="icon icon-chevron-left"></i> <code class="docutils literal"><span class="pre">django-admin</span></code> and <code class="docutils literal"><span class="pre">manage.py</span></code></a></div>
  
  
  <div class="right"><a href="../files/">File handling <i class="icon icon-chevron-right"></i></a></div>
  
</div>



        <a href="#top" class="backtotop"><i class="icon icon-chevron-up"></i> Back to Top</a>
      </div>

      
<h1 class="visuallyhidden">Additional Information</h1>
<div role="complementary">
  
  

<form action="https://docs.djangoproject.com/en/1.10/search/" class="search form-input" role="search">
  <label class="visuallyhidden" for="news-search">Search:</label>
    <input id="id_q" name="q" placeholder="Search 1.10 documentation" type="search" />

    <button type="submit">
      <i class="icon icon-search"></i>
      <span class="visuallyhidden">Search</span>
    </button>
</form>

  

  


  <div class="fundraising-sidebar">
    <h2>Support Django!</h2>

    <div class="small-heart">
      <img src="/s/img/small-fundraising-heart.d255f6e934e5.png" alt="Support Django!" />
    </div>

    <div class="small-cta">
      <ul class="list-links-small">
        <li><a href="https://www.djangoproject.com/fundraising/">
          Denis Golomazov donated to the Django Software Foundation to
          support Django development. Donate today!
        </a></li>
      </ul>
    </div>
  </div>



  
    <h2>Contents</h2>
    
    <ul>
<li><a class="reference internal" href="#">Django Exceptions</a><ul>
<li><a class="reference internal" href="#module-django.core.exceptions">Django Core Exceptions</a><ul>
<li><a class="reference internal" href="#appregistrynotready"><code class="docutils literal"><span class="pre">AppRegistryNotReady</span></code></a></li>
<li><a class="reference internal" href="#objectdoesnotexist"><code class="docutils literal"><span class="pre">ObjectDoesNotExist</span></code></a></li>
<li><a class="reference internal" href="#fielddoesnotexist"><code class="docutils literal"><span class="pre">FieldDoesNotExist</span></code></a></li>
<li><a class="reference internal" href="#multipleobjectsreturned"><code class="docutils literal"><span class="pre">MultipleObjectsReturned</span></code></a></li>
<li><a class="reference internal" href="#suspiciousoperation"><code class="docutils literal"><span class="pre">SuspiciousOperation</span></code></a></li>
<li><a class="reference internal" href="#permissiondenied"><code class="docutils literal"><span class="pre">PermissionDenied</span></code></a></li>
<li><a class="reference internal" href="#viewdoesnotexist"><code class="docutils literal"><span class="pre">ViewDoesNotExist</span></code></a></li>
<li><a class="reference internal" href="#middlewarenotused"><code class="docutils literal"><span class="pre">MiddlewareNotUsed</span></code></a></li>
<li><a class="reference internal" href="#improperlyconfigured"><code class="docutils literal"><span class="pre">ImproperlyConfigured</span></code></a></li>
<li><a class="reference internal" href="#fielderror"><code class="docutils literal"><span class="pre">FieldError</span></code></a></li>
<li><a class="reference internal" href="#validationerror"><code class="docutils literal"><span class="pre">ValidationError</span></code></a><ul>
<li><a class="reference internal" href="#non-field-errors"><code class="docutils literal"><span class="pre">NON_FIELD_ERRORS</span></code></a></li>
</ul>
</li>
</ul>
</li>
<li><a class="reference internal" href="#url-resolver-exceptions">URL Resolver exceptions</a><ul>
<li><a class="reference internal" href="#resolver404"><code class="docutils literal"><span class="pre">Resolver404</span></code></a></li>
<li><a class="reference internal" href="#noreversematch"><code class="docutils literal"><span class="pre">NoReverseMatch</span></code></a></li>
</ul>
</li>
<li><a class="reference internal" href="#database-exceptions">Database Exceptions</a></li>
<li><a class="reference internal" href="#http-exceptions">Http Exceptions</a><ul>
<li><a class="reference internal" href="#unreadableposterror"><code class="docutils literal"><span class="pre">UnreadablePostError</span></code></a></li>
</ul>
</li>
<li><a class="reference internal" href="#transaction-exceptions">Transaction Exceptions</a><ul>
<li><a class="reference internal" href="#transactionmanagementerror"><code class="docutils literal"><span class="pre">TransactionManagementError</span></code></a></li>
</ul>
</li>
<li><a class="reference internal" href="#testing-framework-exceptions">Testing Framework Exceptions</a><ul>
<li><a class="reference internal" href="#redirectcycleerror"><code class="docutils literal"><span class="pre">RedirectCycleError</span></code></a></li>
</ul>
</li>
<li><a class="reference internal" href="#python-exceptions">Python Exceptions</a></li>
</ul>
</li>
</ul>

    
  

  
  <h2>Browse</h2>
  <ul>
    
    
    <li>Prev: <a href="../django-admin/"><code class="docutils literal"><span class="pre">django-admin</span></code> and <code class="docutils literal"><span class="pre">manage.py</span></code></a></li>
    
    
    <li>Next: <a href="../files/">File handling</a></li>
    
    <li><a href="https://docs.djangoproject.com/en/1.10/contents/">Table of contents</a></li>
    
    <li><a href="https://docs.djangoproject.com/en/1.10/genindex/">General Index</a></li>
    
    <li><a href="https://docs.djangoproject.com/en/1.10/py-modindex/">Python Module Index</a></li>
    
    
  </ul>
  

  
  <h2>You are here:</h2>
  <ul>
    <li>
      <a href="https://docs.djangoproject.com/en/1.10/">Django 1.10 documentation</a>
      
      <ul><li><a href="../">API Reference</a>
      
      <ul><li>Django Exceptions</li></ul>
      </li></ul>
    </li>
  </ul>
  

  
  <h2 id="getting-help-sidebar">Getting help</h2>
  <dl class="list-links">
    <dt><a href="https://docs.djangoproject.com/en/1.10/faq/">FAQ</a></dt>
    <dd>Try the FAQ — it's got answers to many common questions.</dd>

    <dt><a href="/en/stable/genindex/">Index</a>, <a href="/en/stable/py-modindex/">Module Index</a>, or <a href="/en/stable/contents/">Table of Contents</a></dt>
    <dd>Handy when looking for specific information.</dd>

    <dt><a href="http://groups.google.com/group/django-users/">django-users mailing list</a></dt>
    <dd>Search for information in the archives of the django-users mailing list, or post a question.</dd>

    <dt><a href="irc://irc.freenode.net/django">#django IRC channel</a></dt>
    <dd>Ask a question in the #django IRC channel, or search the IRC logs to see if it’s been asked before.</dd>

    <dt><a href="http://code.djangoproject.com/">Ticket tracker</a></dt>
    <dd>Report bugs with Django or Django documentation in our ticket tracker.</dd>
  </dl>
  

  
  <h2>Download:</h2>
  <p>
    Offline (Django 1.10):
    <a href="/m/docs/django-docs-1.10-en.zip">HTML</a> |
    <a href="https://media.readthedocs.org/pdf/django/1.10.x/django.pdf">PDF</a> |
    <a href="https://media.readthedocs.org/epub/django/1.10.x/django.epub">ePub</a>
    <br>
    <span class="quiet">
      Provided by <a href="https://readthedocs.org/">Read the Docs</a>.
    </span>
  </p>
  
</div>

      

    </div>

     
     

    
    
    

    
      
<div role="contentinfo">
  <div class="subfooter">
    <div class="container">
      <h1 class="visuallyhidden">Django Links</h1>

      <div class="col learn">
        <h2>Learn More</h2>
        <ul>
          <li><a href="https://www.djangoproject.com/start/overview/">About Django</a></li>
          
          <li><a href="https://www.djangoproject.com/start/">Getting Started with Django</a></li>
          <li><a href="https://docs.djangoproject.com/en/dev/internals/organization/">Team Organization</a></li>
          <li><a href="https://www.djangoproject.com/foundation/">Django Software Foundation</a></li>
          <li><a href="https://www.djangoproject.com/conduct/">Code of Conduct</a></li>
          <li><a href="https://www.djangoproject.com/diversity/">Diversity statement</a></li>
        </ul>
      </div>

      <div class="col involved">
        <h2>Get Involved</h2>
        <ul>
          <li><a href="https://www.djangoproject.com/community/">Join a Group</a></li>
          <li><a href="https://docs.djangoproject.com/en/dev/internals/contributing/">Contribute to Django</a></li>
          <li><a href="https://docs.djangoproject.com/en/dev/internals/contributing/bugs-and-features/">Submit a Bug</a></li>
          <li><a href="https://docs.djangoproject.com/en/dev/internals/security/#reporting-security-issues">Report a Security Issue</a></li>
        </ul>
      </div>

      <div class="col follow last-child">
        <h2>Follow Us</h2>
        <ul>
          <li><a href="https://github.com/django">GitHub</a></li>
          <li><a href="https://twitter.com/djangoproject">Twitter</a></li>
          <li><a href="https://www.djangoproject.com/rss/weblog/">News RSS</a></li>
          <li><a href="https://groups.google.com/forum/#!forum/django-users">Django Users Mailing List</a></li>
        </ul>
      </div>

    </div>
  </div>

  <div class="footer">
    <div class="container">
      <div class="footer-logo">
        <a class="logo" href="https://www.djangoproject.com/">Django</a>
      </div>
      <ul class="thanks">
        <li>
          <span>Hosting by</span> <a class="rackspace" href="http://rackspace.com">Rackspace</a>
          <span>Search by</span> <a class="elastic" href="https://www.elastic.co">Elastic Search</a>
        </li>
        <li class="design"><span>Design by</span> <a class="threespot" href="http://www.threespot.com">Threespot</a> <span class="ampersand">&amp;</span> <a class="andrevv" href="http://andrevv.com/"></a></li>
      </ul>
      <p class="copyright">&copy; 2005-2016
        <a href="https://www.djangoproject.com/foundation/"> Django Software
        Foundation</a> and individual contributors. Django is a
        <a href="https://www.djangoproject.com/trademarks/">registered
        trademark</a> of the Django Software Foundation.
      </p>
    </div>
  </div>

</div>

    

    
    <script>
    function extless(input) {
        return input.replace(/(.*)\.[^.]+$/, '$1');
    }
    var require = {
        shim: {
            'jquery': [],
            'jquery.inview': ["jquery"],
            'jquery.payment': ["jquery"],
            'jquery.flot': ["jquery"],
            'jquery.unveil': ["jquery"],
            'stripe': {
              exports: 'Stripe'
            }
        },
        paths: {
            "jquery": extless("/s/js/lib/jquery/dist/jquery.min.87e69028f78d.js"),
            "jquery.inview": extless("/s/js/lib/jquery.inview/jquery.inview.min.4edba1c65592.js"),
            "jquery.payment": extless("/s/js/lib/jquery.payment/lib/jquery.payment.e99c05ca79ae.js"),
            "jquery.unveil": extless("/s/js/lib/unveil/jquery.unveil.min.ac79eb277093.js"),
            "jquery.flot": extless("/s/js/lib/jquery-flot/jquery.flot.min.9964206e9d7f.js"),
            "clipboard": extless("/s/js/lib/clipboard/dist/clipboard.min.bd70fd596a23.js"),
            "mod/floating-warning": extless("/s/js/mod/floating-warning.a21b2abd2884.js"),
            "mod/list-collapsing": extless("/s/js/mod/list-collapsing.c1a08d3ef9e9.js"),
            "mod/list-feature": extless("/s/js/mod/list-feature.73529480f25b.js"),
            "mod/mobile-menu": extless("/s/js/mod/mobile-menu.841726ee903a.js"),
            "mod/version-switcher": extless("/s/js/mod/version-switcher.c28bb83972bb.js"),
            "mod/search-key": extless("/s/js/mod/search-key.f3c0a6fcfedd.js"),
            "mod/stripe-custom-checkout": extless("/s/js/mod/stripe-custom-checkout.e299868f75aa.js"),
            "mod/stripe-change-card": extless("/s/js/mod/stripe-change-card.c9e3d05f7a91.js"),
            "stripe-checkout": "https://checkout.stripe.com/checkout",
            "stripe": "https://js.stripe.com/v2/?"  // ? needed due to require.js
        }
    };
    </script>
    <script data-main="/s/js/main.3a2ae4b1529c.js" src="/s/js/lib/require.177879fbe7dd.js"></script>
    



  </body>
</html>
